apiVersion: v1
kind: Service
metadata:
  name: codedolphin-web
  namespace: codedolphin
  labels:
    app: codedolphin
spec:
  type: ClusterIP
  selector:
    app: codedolphin
  ports:
    - name: http
      port: 80
      targetPort: http
